### ISSUE TITLE
Authoriation Issue

### ISSUE THREAD

**Issue by Pchsen97** [tourist1998/Xcomp#6]
There is a security issue in authorization, Anyone can access and modify my post

**Comment by tourist1998** [comment]
For authorization purpose, JSON web token are best to use. Once the user is logged in, each subsequent request will include the JWT, allowing the user to access routes, services, and resources that are permitted with that token. Single Sign-On is a feature that widely uses JWT nowadays, because of its small overhead and its ability to be easily used across different domains.

In authentication, when the user successfully logs in using their credentials, a JSON Web Token will be returned. Since tokens are credentials, great care must be taken to prevent security issues. In general, you should not keep tokens longer than required. You just need to pass this token using cookies and will be saved in the user's system for a given time until it is expires. You can verify the user otherwise create error.
